const divisions = [
  {
    id: 1,
    name: "Dhaka",
    bn_name: "ঢাকা",
    capital: "Dhaka",
    latitude: 23.8103,
    longitude: 90.4125,
    districts_count: 13,
  },
  {
    id: 2,
    name: "Chattogram",
    bn_name: "চট্টগ্রাম",
    capital: "Chattogram",
    latitude: 22.3569,
    longitude: 91.7832,
    districts_count: 11,
  },
  {
    id: 3,
    name: "Rajshahi",
    bn_name: "রাজশাহী",
    capital: "Rajshahi",
    latitude: 24.3745,
    longitude: 88.6042,
    districts_count: 8,
  },
  {
    id: 4,
    name: "Khulna",
    bn_name: "খুলনা",
    capital: "Khulna",
    latitude: 22.8456,
    longitude: 89.5403,
    districts_count: 10,
  },
  {
    id: 5,
    name: "Barishal",
    bn_name: "বরিশাল",
    capital: "Barishal",
    latitude: 22.701,
    longitude: 90.3535,
    districts_count: 6,
  },
  {
    id: 6,
    name: "Sylhet",
    bn_name: "সিলেট",
    capital: "Sylhet",
    latitude: 24.8949,
    longitude: 91.8687,
    districts_count: 4,
  },
  {
    id: 7,
    name: "Rangpur",
    bn_name: "রংপুর",
    capital: "Rangpur",
    latitude: 25.7439,
    longitude: 89.2752,
    districts_count: 8,
  },
  {
    id: 8,
    name: "Mymensingh",
    bn_name: "ময়মনসিংহ",
    capital: "Mymensingh",
    latitude: 24.7471,
    longitude: 90.4203,
    districts_count: 4,
  },
];
